name: Trigger Discord Webhook (Actions Repo)

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, closed ]
  issues:
    types: [ opened, edited, closed ]

jobs:
  trigger-actions-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Discord Webhook
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          GITHUB_EVENT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          set -e
          
          EVENT_TYPE="${{ github.event_name }}"
          if [[ "$EVENT_TYPE" == "push" ]]; then
            EVENT_TYPE="commit"
          elif [[ "$EVENT_TYPE" == "pull_request" ]]; then
            EVENT_TYPE="pull-request"
          elif [[ "$EVENT_TYPE" == "issues" ]]; then
            EVENT_TYPE="issues"
          fi
          
          MSG="$(jq -r '.head_commit.message // "No commit message"' <<< '${{ toJson(github.event) }}')"
          if [ -z "$MSG" ]; then
            MSG="No commit message"
          fi
          
          PAYLOAD=$(jq -n \
            --arg repo "${{ github.repository }}" \
            --arg branch "${{ github.ref_name }}" \
            --arg event "$EVENT_TYPE" \
            --arg sha "${{ github.sha }}" \
            --arg msg "$MSG" \
            --arg author "${{ github.actor }}" \
            '{repo_name: $repo, branch_name: $branch, event_type: $event, commit_sha: $sha, commit_message: $msg, commit_author: $author}'
          )
          
          gh workflow run github-to-discord.yml \
            --repo ririf4/Actions \
            --ref main \
            -f payload="$PAYLOAD"
