name: Use GitHub to Discord Webhook
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, closed ]
  issues:
    types: [ opened, edited, closed ]
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

jobs:
  call-common-webhook:
    uses: ririf4/Actions/.github/workflows/github-to-discord.yml@main
    with:
      event_type: ${{ github.event_name }}
    secrets:
      DISCORD_COMMIT_WEBHOOK: ${{ secrets.DISCORD_COMMIT_WEBHOOK }}
      DISCORD_PR_WEBHOOK: ${{ secrets.DISCORD_PR_WEBHOOK }}
      DISCORD_ISSUE_WEBHOOK: ${{ secrets.DISCORD_ISSUE_WEBHOOK }}
